name: Poll Azure DevOps for Testing Cards

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 10 minutes
  workflow_dispatch:

jobs:
  poll-ado:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests python-dotenv

      - name: Poll Azure DevOps for Testing cards
        env:
          ADO_ORG_URL: ${{ secrets.ADO_ORG_URL }}
          ADO_PROJECT: ${{ secrets.ADO_PROJECT }}
          ADO_PAT: ${{ secrets.ADO_PAT }}
        run: python .github/scripts/poll_ado_and_trigger.py
